---
name: EssentialsPE
version: 1.0
main: Tinajero\EssentialsPE\Main
api: 4.5.1
src-namespace-prefix: Tinajero\EssentialsPE
permissions:
 ess.fly:
  default: false
 ess.gmc:
  default: false
 ess.gms:
  default: false
 ess.feed:
  default: false
 ess.heal:
  default: false
 ess.nightvision:
  default: false
...
